### ISSUE TITLE
keys.py???

### ISSUE THREAD

**Issue by mathurin68** [CIRCL/PyMISP#20]
Alright, I'm a moron and new to python but are we supposed to create our own keys.py?  I don't suppose you guys have an example for a newbie?  

We're trying to get data shared between CIF/Taxii/MISP... hoping this is the answer!

**Comment by adulau** [comment]
If you do an import of the key from your Python code:

~~~
from keys import url, key
~~~

You have to create a keys.py file with the following:

~~~
url = 'http://misp.yourorganisation.something'
key = 'AUTH KEY'
~~~

We also recommend to put this file in the exclude list of your git configuration in order to avoid any unintentional commit.  I hope this helps.

**Comment by mathurin68** [comment]
Thank you!  Thats what I thought... I got confused on what url_priv and url_cert were and then where api.py fit in... 

For what we want to do at the moment with MISP is mostly act as a 'correlating hub' between all our security tools; and then in the future start to share info with other agencies.

Hah dont get me started on questions about git.

Thank you very much for yoyr time!
