### ISSUE TITLE
Add an option 'publish without email'

### ISSUE THREAD

**Issue by devnull-** [CIRCL/PyMISP#70]
Hello all,

Could you consider to add an option "without_email" on the function [publish](https://github.com/CIRCL/PyMISP/blob/1d8af6eb70bb4ea25711c9357db320ff023e6e9a/pymisp/api.py#L329):

```
    def publish(self, event, without_email=False or True):
      ....
```

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

**Comment by Rafiot** [comment]
@iglocska how does it look like on server side?

**Comment by iglocska** [comment]
Hmm that is currently not possible. I wonder what the cleanest way of doing it would be.

Basically we are not really publishing an event via PyMISP, what happens is we push an event that is already set to be published. Now since any edit to an event causes it to be unpublished, this will automatically trigger a publishing, but we don't explicitly trigger it.

So what we could do: Open up the publish/alert functions in MISP to be accessible via the API and decouple it in PyMISP. That way we could choose to simply just publish (no email) or alert (publish with email). How does that sound? Of course it would add extra complexity to PyMISP...

**Comment by Rafiot** [comment]
It probably makes sense to make the event publication with/without email possible from the API. But I'll clearly have to find a way to make it cleanly on API side... Not totally sure how, but that should be possible.

**Comment by adulau** [comment]
@iglocska The decouple API makes sense to me as the functionality is there in the UI.

**Comment by cvandeplas** [comment]
Considering the new functionality that when you add a tag, the event is unpublished, this feature request becomes more important.

**Comment by tking2** [comment]
Hey @Rafiot, I can't see what change in commit 52a87cc resolves the issue of publishing without an email alert, as these options seem to relate to set individual user accounts email alerts.

**Comment by Rafiot** [comment]
Sorry for that, it it was fixing the issue 70 on MISP/PyMISP...

**Comment by Rafiot** [comment]
This has been fixed: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L388
