### ISSUE TITLE
Improvements in the user api

### ISSUE THREAD

**Issue by Rafiot** [CIRCL/PyMISP#71]
Right now, creating a new user requires to have a file on the disk[1]. It would be good to have a way to do it by just passing parameters to the function.

@Delta-Sierra: can you add this functionality, please? But also keep the file-path option.

@iglocska: if there are any, what are the default values? I like to keep it consistent between PyMISP and MISP.

[1] https://github.com/CIRCL/PyMISP/blob/master/pymisp/api.py#L1115

**Comment by iglocska** [comment]
Basically for default values, you don't have to worry about them, MISP will create them automatically. The only things that are needed are the e-mail address, org_id and role_id. The rest is all optional.

If you run a GET on /admin/users/add it returns a JSON with all mandatory and optional options. I want to slowly move all APIs to this system :)

**Comment by Delta-Sierra** [comment]
I tried something even if it might not be the better way to handle it, here : https://github.com/MISP/PyMISP/commit/3cadc1a78d1689e8b0e68eb8666bf6595f872c40
I splited the cases when you have a json or not, and I also made similar changes for edit_user (in order to be consistent).
Functions and examples have been added corrected/renamed to match the different cases.

Please tell if it is okay for you :)

**Comment by Rafiot** [comment]
Great, thanks :) 

Just a small detail: maybe create a private function with all the parameters in order to deduplicate the code in the edit and add methods.

**Comment by Rafiot** [comment]
Done.
