### ISSUE TITLE
allow search on attribute level

### ISSUE THREAD

**Issue by cvandeplas** [CIRCL/PyMISP#80]
A missing feature is to search for attributes, and get attributes returned.
Also a full-text match would be needed.

Today the only way is `search()` returning an events list, however this also matches on partial results.
example:  database contains "www.domain.tld", you search for "domain.tld" and get a result.

**Comment by Rafiot** [comment]
If you pass `controller='attributes'` to `search`: https://github.com/CIRCL/PyMISP/blob/master/pymisp/api.py#L819
You only get the attributes.

If you want to search `domain.tld` and you only want domains, you can pass `['domain']` to `type_attribute`. 

But that's a good point we should have an exact match only (instead of full text search). @iglocska how hard would it be to implement?

**Comment by Rafiot** [comment]
Moved over there: https://github.com/MISP/PyMISP/issues/136
